---
title: "Chord Diagram for Different Genres"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(chorddiag)
library(reshape2)
library(hash)
library(data.table)
library(dplyr)



load("Diagrams.Rdata")
load("DiagramsData.Rdata")
load("GenreTDM.Rdata")

##### for color matching ######
# in total 12 kinds of chords      
chord.Vec<-c("A","Ab","B","Bb","C","D","Db","E","Eb","F#","F","G")
color.Vec<-c("#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462",
  "#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f")
colormap<-hash(chord.Vec,color.Vec)

#assign each matrix for chord diagram color in a consitent way

colormatch<-function(Mat){
  chords<-rownames(Mat)
  m<-unlist(lapply(strsplit(as.character(chords), split=":"),head, n=1))
 
  colorgroup<-values(colormap,keys=m)
  colorgroup<-as.vector(colorgroup)
  return (colorgroup)
}

################################################

All_Genre_Matrix<-list()
All_Genre_color<-list()
for(i in 1:8){
  MyGenre<-rownames(Genre_Matrix2_tfidf)[i]  #specify a genre
  
  g_id<-i
  df<-as.data.frame(Genre_Matrix2[g_id,])
  setDT(df, keep.rownames = TRUE)
  colnames(df)<-c("ngrams","freq")
  #df<-Genre2Gram
  
  X<-with(df, cbind( colsplit(df$ngrams, pattern = "\\s", names = c('from', 'to')),freq))
  X$to <- gsub('\\s', '', X$to)
  tmp<-acast(X,from~to,value.var='freq', fun.aggregate = sum)
  tmp[is.na(tmp)]<-0
  dimnames(tmp) <- list(from = colnames(tmp), to = colnames(tmp))
  
  Top2G<-colnames(Genre_Matrix2_tfidf)[sort.list(Genre_Matrix2_tfidf[g_id,],decreasing = TRUE)[1:30]]
  Top2G<-unique(unlist(strsplit(Top2G,split=" ")))
  Genre.Top2G.Matrix<-tmp[which(rownames(tmp) %in% Top2G),which(rownames(tmp) %in% Top2G)]
  Genre.Top2G.Color<-colormatch(Genre.Top2G.Matrix)
  
  All_Genre_Matrix[[i]]<-Genre.Top2G.Matrix
  All_Genre_color[[i]]<-Genre.Top2G.Color
  
} 


```

Row 
-----------------------------------------------------------------------

### R&B/Soul

```{r}


chorddiag(All_Genre_Matrix[[1]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[1]],margin=35)

```

### Rock

```{r}
chorddiag(All_Genre_Matrix[[2]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[2]],margin=35)
```

### Pop

```{r}
chorddiag(All_Genre_Matrix[[3]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[3]],margin=35)
```


### Country

```{r}
chorddiag(All_Genre_Matrix[[4]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[4]],margin=35)
```


Row
-----------------------------------------------------------------------

### Others

```{r}
chorddiag(All_Genre_Matrix[[5]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[5]],margin=35)

```


### Hip-hop

```{r}
chorddiag(All_Genre_Matrix[[6]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[6]],margin=35)

```

### Folk

```{r}
chorddiag(All_Genre_Matrix[[7]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[7]],margin=35)

```


### Jazz

```{r}
chorddiag(All_Genre_Matrix[[8]],groupnameFontsize=8,groupnamePadding = 5,showTicks = FALSE,chordedgeColor =NULL,palette = "Set3",groupColors =All_Genre_color[[8]],margin=35)

```