---
title: "Sankey Diagram"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 4-Gram 

```{r}
library(ngram)

x = load("/Users/mac/Documents/Fall2016-proj5-grp2/Cen-s-billboard-data-processing/cleaned_data.RData")


chord_use_positions = sapply(all.chord.original.sd, function(x) x[1])

chord_use_positions = as.integer(chord_use_positions)
chord_use = all.chord.original.sd
names(chord_use) = chord_use_positions
#find the used song  chord
#match_pos = match(songuse$id, chord_use_positions)
#pos = na.omit(as.character(chord_use_positions[match_pos]))
#chord_use = chord_use[pos]  #872 songs actual
#name use the song used id and remove the first id in list
#names(chord_use) = pos
#chord_use = lapply(chord_use, function(x) x[-1])

#concatenate chords
chord_use_concatenated = lapply(chord_use, concatenate, 
                                collapse = " ", rm.space = FALSE)


lens =lapply(chord_use_concatenated, function(x) length(strsplit(x, split = " ")[[1]]))
poses = unlist(lens)
poses_rm = which(!poses >= 4)
chord_use_concatenated = chord_use_concatenated[-poses_rm ]

chord_use_4_grams = lapply(chord_use_concatenated, ngram, n = 4, sep = " ")
```  

#diff genre for 4-gram
```{r}
library(dplyr)

setwd("~/Documents/Fall2016-proj5-grp2/data/Billboard")

genre <- read.csv("final_genre.csv", header = T)

GenreName<-unique(genre[,'genre'])

All_Genres_Chords<-list()

for(k in GenreName){  # k=Country/Folk/Hip-hop/Jazz/Others/Pop/R&BSoul/Rock)
  genre_id<-filter(genre,genre==k)[,'id']
  All_Genres_Chords[[k]]<-"" #a string to store all Chords in Genre k
  j=1
  #extract the chords of kth genre 
  for(i in 1:length(chord_use)){
    if(as.numeric(chord_use[[i]][1]) %in% genre_id){
      tmp.str<-paste(chord_use[[i]][-1], collapse=" ") #merge elements into strings
      All_Genres_Chords[[k]]<-paste(All_Genres_Chords[[k]],tmp.str)
      All_Genres_Chords[[k]]<-paste(All_Genres_Chords[[k]],"\n")
      j<-j+1
    }
  }
  
}

genre_use_4_grams = lapply(All_Genres_Chords, ngram, n = 4, sep = " ")
head(get.phrasetable(genre_use_4_grams$`R&B/Soul`), 6)
head(get.phrasetable(genre_use_4_grams$Rock), 6)
head(get.phrasetable(genre_use_4_grams$Pop), 6)
head(get.phrasetable(genre_use_4_grams$Country), 6)
head(get.phrasetable(genre_use_4_grams$Others), 6)
head(get.phrasetable(genre_use_4_grams$`Hip-hop`), 6)
head(get.phrasetable(genre_use_4_grams$Folk), 6)
head(get.phrasetable(genre_use_4_grams$Jazz), 6)
```


#topic model use 4-gram


```{r}

library(stringr)

songs_chords = c()
for(i in 1:length(chord_use_4_grams)) {
a = get.phrasetable(chord_use_4_grams[[i]])
a[,1] = str_trim(a[,1])
a[,1] = gsub(" ","->",a[,1])
strs = rep(a[,1], a[,2])
strs = paste(strs, collapse = " ")
songs_chords = c(songs_chords, strs)
}

library(topicmodels)

library(NLP)

library(tm)

chords_use = songs_chords

chords_use=enc2utf8(chords_use)

#generate corpus
doc.vec = VectorSource(chords_use)
doc.corpus = Corpus(doc.vec)


TDM = TermDocumentMatrix(doc.corpus)
DTM = DocumentTermMatrix(doc.corpus)

library(slam)
#USE tfidf to extract key chords
term_tfidf =tapply(DTM$v/row_sums(DTM)[DTM$i], DTM$j, mean) *log2(nDocs(DTM)/col_sums(DTM > 0))
DTM = DTM[,term_tfidf >= 0.1]
DTM = DTM[row_sums(DTM) > 0,]

#construct LDA model
lda.chords_use = LDA(DTM, k = 5, method="VEM", control = list(seed = 1500))
summary(lda.chords_use)

#topic of each song
topic1=topics(lda.chords_use,1)
data.frame(topic1)
#key chords of each topic
terms(lda.chords_use, 20)
```

#Color of chord
```{r}
library(hash)
chord.Vec<-c("A","Ab","B","Bb","C","D","Db","E","Eb","F#","F","G")
color.Vec<-c("#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462",
 "#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f")
colormap<-hash(chord.Vec,color.Vec)


colormatch<-function(chords){
 #chords<-rownames(Mat)
 m<-unlist(lapply(strsplit(as.character(chords), split=":"),head, n=1))

 colorgroup<-values(colormap,keys=m)
 colorgroup<-as.vector(colorgroup)
 return (colorgroup)
}

```


#Sankey diagram using chords 
```{r}

library(networkD3)

All_Chords<-""
for(i in 1:length(all.chord.original.sd)){
 tmp.str<-paste(all.chord.original.sd[[i]][-1], collapse=" ") #merge elements into strings
 All_Chords<-paste(All_Chords,tmp.str)
 All_Chords<-paste(All_Chords,"\n")
}

all_NG = lapply(All_Chords, ngram, n = 4, sep = " ")
all_NG <- ngram(All_Chords,4)
all_chord_ngram <- get.phrasetable(all_NG)


whole = NULL

ids = as.numeric(names(all_NG))

genres_ids = genre[match(ids, genre$id), "genre"]

for(i in 1:length(all_NG)) {
  a = get.phrasetable(all_NG[[i]])
  whole = rbind(whole, cbind(a[,1:2], genres = as.character(genres_ids)[i]))
}

whole_merge = aggregate(freq ~ ngrams, data = whole, sum) 
gen = subset(whole, genre == as.character(us))
head(whole_merge)
dim(whole_merge)

whole_merge2 = whole_merge[rev(order(whole_merge$freq)),]

head(whole_merge2)

whole_merge3 = whole_merge2


whole_merge4 = NULL



for(i in 1:nrow(whole_merge3)) {
  whole_merge4 = rbind(whole_merge4, c(strsplit(whole_merge3[i,1], 
                                                split= " ")[[1]], 
                                       whole_merge3[i,2]))
}

head(whole_merge4)
whole_merge4 = head(whole_merge4, n = 100)
c1 = unique(whole_merge4[,1])

c2 = unique(whole_merge4[,2])

c3 = unique(whole_merge4[,3])

c4 = unique(whole_merge4[,4])

us = unique(genre$genre)

nodes = data.frame(name = c("Start",c1,c2,c3,c4),stringsAsFactors = F)
names = data.frame(name = c(c1,c2,c3,c4), stringsAsFactors = F)
colors = colormatch(names$name)

p1 = match(whole_merge4[,1],c1) - 1 + 1
p2 = match(whole_merge4[,2],c2) - 1 + length(c1) + 1
p3 = match(whole_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
p4 = match(whole_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
dt = rbind(
  data.frame(a=p1, b=p2, d=whole_merge4[,5]) ,
  data.frame(a=p2, b=p3, d=whole_merge4[,5])
 )
dt2 = rbind(dt, data.frame(a=p3, b=p4, d=whole_merge4[,5]))
dt_g = data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
dt2 = rbind(dt_g,dt2)
dt2[,3] = as.integer(as.character(dt2[,3]))
links = dt2
colnames(links) = c("source","target","value")
links2 = aggregate(value ~ source + target, data = links, sum)
links2 = data.frame(links2, group = "genres")
sankeyNetwork(Links = links2, Nodes = nodes,
              Source = "source", Target = "target",
              Value = "value", NodeID = "name")




us = unique(genre$genre)
g = us[1]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  
  



us = unique(genre$genre)
g = us[2]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  

us = unique(genre$genre)
g = us[3]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  us = unique(genre$genre)
g = us[4]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  
  
  
  us = unique(genre$genre)
g = us[5]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  
  us = unique(genre$genre)
g = us[6]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
us = unique(genre$genre)
g = us[7]
gen = subset(whole, genre == as.character(g))
gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
head(gen_merge)
dim(gen_merge)
gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
head(gen_merge2)
gen_merge3 = gen_merge2
gen_merge4 = NULL
for(i in 1:nrow(gen_merge3)) {
  gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
}
head(gen_merge4)
c1 = unique(gen_merge4[,1])
c2 = unique(gen_merge4[,2])
c3 = unique(gen_merge4[,3])
c4 = unique(gen_merge4[,4])
nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
p1=match(gen_merge4[,1],c1) - 1 + 1
p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
dt = rbind(
  data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
  data.frame(a=p2, b=p3, d=gen_merge4[,5])
 )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  
  us = unique(genre$genre)
g = us[8]
  
  gen = subset(whole, genre == as.character(g))
  
  gen_merge = aggregate(freq ~ ngrams, data = gen,sum)  
  
  head(gen_merge)
  
  dim(gen_merge)
  
  gen_merge2 = gen_merge[rev(order(gen_merge$freq)),]
  
  head(gen_merge2)
  
  gen_merge3 = gen_merge2
  
  
  gen_merge4 = NULL
  
  
  
  for(i in 1:nrow(gen_merge3)) {
    gen_merge4 = rbind(gen_merge4, c(strsplit(gen_merge3[i,1],split= " ")[[1]],gen_merge3[i,2]))
  }
  
  head(gen_merge4)
  c1 = unique(gen_merge4[,1])
  
  c2 = unique(gen_merge4[,2])
  
  c3 = unique(gen_merge4[,3])
  
  c4 = unique(gen_merge4[,4])
  
  
  
  
  nodes = data.frame(name = c(as.character(g),c1,c2,c3,c4),stringsAsFactors = F)
  
  
  p1=match(gen_merge4[,1],c1) - 1 + 1
  p2= match(gen_merge4[,2],c2) - 1 + length(c1) + 1
  p3= match(gen_merge4[,3],c3) - 1 + length(c1) + length(c2) + 1
  p4 = match(gen_merge4[,4],c4) - 1 + length(c1) + length(c2) + length(c3) + 1
  
  dt = rbind(
    data.frame(a=p1, b=p2, d=gen_merge4[,5]) ,
    data.frame(a=p2, b=p3, d=gen_merge4[,5])
  )
  
  
  dt2 = rbind(dt,
              data.frame(a=p3, b=p4, d=gen_merge4[,5])
  )
   dt_g =  data.frame(a=0, b=p1, d=dt[1:length(p1),3])  
  
  dt2 = rbind(dt_g,dt2)
  
  dt2[,3] = as.integer(as.character(dt2[,3]))
  
  
  
 
  
  links = dt2
  colnames(links) = c("source","target","value")
  
  
  links2 = aggregate(value ~ source + target, data = links, sum)
  links2 = data.frame(links2, group =g)
  sankeyNetwork(Links = links2, Nodes = nodes,
                Source = "source", Target = "target",
                Value = "value", LinkGroup = "group", NodeID = "name")
  
  
  

```

